# fly.toml app configuration file generated for my-app-holy-forest-3609 on 2024-11-12T16:43:25-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'my-app-holy-forest-3609'
primary_region = 'ord'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[env]
  BODY_SIZE_LIMIT = 4811090

[[vm]]
  memory = '2gb'
  cpu_kind = 'shared'
  cpus = 1